### ISSUE TITLE
Multiple Now Connected messages

### ISSUE THREAD

**Issue by elyobelyob** [SR-G/current-cost-forwarder#1]
Hi,

Trying this out on a Raspberry Pi, I just seem to get lots of Now Connected messages.

17:55:38.684 [main] INFO  org.tensin.ccf.CurrentCostForwarder - Now starting reader
17:55:38.695 [main] INFO  org.tensin.ccf.reader.CurrentCostReader - Trying to autodect mirror4j device in [/dev/] with pattern [ttyUSB.*]
17:55:38.792 [main] INFO  org.tensin.ccf.reader.CurrentCostReader - Auto-detected current cost device [/dev/ttyUSB0]
17:55:38.913 [main] INFO  org.tensin.ccf.reader.CurrentCostReader - Starting CurrentCostForwarder reader thread on device [/dev/ttyUSB0]
17:55:38.915 [main] INFO  org.tensin.ccf.CurrentCostForwarder - CurrentCostForwarder started in [572ms]
17:55:38.918 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:39.020 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:39.120 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:39.220 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:39.320 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:39.420 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:39.520 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:39.620 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:39.720 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:39.820 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:39.920 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:40.020 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:40.120 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:40.220 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:40.320 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
17:55:40.420 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]

**Comment by SR-G** [comment]
With such a high rate, I guess it doesn't work on your side because it constantly disconnects/reconnects.
Are you sure your current cost device is on /dev/ttyUSB0 ?
What are your permissions on /dev/ttyUSB0 ?

On my side i have :

> cubox-i# ll /dev/tty*USB*
> crw-rw---T 1 root dialout 188, 0 Jan  1  1970 /dev/ttyUSB0

And : 

> cubox-i# lsusb
> Bus 001 Device 002: ID 1da8:1301
> Bus 002 Device 002: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port

I'll check the code to see why you don't have any exceptions / additionnal informations (maybe in the meanwhile you could add the --debug parameter in the .sh or at your launch command).

**Comment by elyobelyob** [comment]
Thanks for response.

pi@raspberrypi ~/currentcost $ ls -l /dev/ttyUSB0
crw-rw---T 1 root dialout 188, 0 Feb  5 18:45 /dev/ttyUSB0

pi@raspberrypi ~/currentcost $ lsusb
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 007: ID 04d9:1603 Holtek Semiconductor, Inc. Keyboard
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp.
Bus 001 Device 004: ID 05e3:0608 Genesys Logic, Inc. USB-2.0 4-Port HUB
Bus 001 Device 005: ID 05e3:0608 Genesys Logic, Inc. USB-2.0 4-Port HUB
Bus 001 Device 006: ID 174c:5106 ASMedia Technology Inc. Transcend StoreJet
25M3
Bus 001 Device 010: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial
Port

I am running the currentcost through a 7 port powered hub, as I have moved
the OS onto a HDD. Could that be anything to do with it?

**Comment by SR-G** [comment]
Ok so : 
- i've checked the code, every errors should be logged (CurrentCostReader.java : either on initial connections (initFileInputStreamDevice()), either on main loop (read()), either on parsing errors (process())) (but i could of course have missed something)
- the --debug parameter would shown an additionnal debug log indicating an XML has been received but can't be parsed (you should be able to launch it with "current-cost-forward.sh --debug"). Could you try this ?
- do you have any other other devices on /dev/ttyUSB* (/dev/ttyUSB1, ...) or only USB0 ? As a quick reminder, the program takes by default the first device (/dev/ttyUSB0), if multiple ones are available you have to specify the right one with "--device /dev/ttyUSB1" (for example)
- as far as i can tell, it should not be related to your additionnal usb hub, but i've never tryied ... raspberry pi is quite freakish about USB powered devices (but things are better with B+), but the current cost is not powered by the pi.
  (i'm running all those devices on a cubie box now on my side)

**Comment by elyobelyob** [comment]
Am running the latest Raspbian on a pi2 ... 

There is only ttyUSB0, no *1's

pi@raspberrypi ~/currentcost $ ls /dev/ttyU*
/dev/ttyUSB0

with debug on...

pi@raspberrypi ~/currentcost $ ./current-cost-forwarder.sh --debug
0 [main] INFO org.tensin.ccf.boot.CurrentCostForwarder - Classpath :
     initial classpath=
      - /home/pi/currentcost/lib/current-cost-forwarder-1.0.0-SNAPSHOT.jar
     dynamic classpath=
      - /home/pi/currentcost/lib/commons-collections-3.2.1.jar
      - /home/pi/currentcost/lib/commons-io-2.4.jar
      - /home/pi/currentcost/lib/commons-lang3-3.1.jar
      - /home/pi/currentcost/lib/commons-logging-1.2.jar
      - /home/pi/currentcost/lib/commons-net-3.2.jar
      - /home/pi/currentcost/lib/dom4j-1.6.1.jar
      - /home/pi/currentcost/lib/guava-17.0.jar
      - /home/pi/currentcost/lib/javassist-3.12.1.GA.jar
      - /home/pi/currentcost/lib/jcommander-1.30.jar
      - /home/pi/currentcost/lib/log4j-1.2-api-2.1.jar
      - /home/pi/currentcost/lib/log4j-api-2.1.jar
      - /home/pi/currentcost/lib/log4j-core-2.1.jar
      - /home/pi/currentcost/lib/log4j-jcl-2.1.jar
      - /home/pi/currentcost/lib/log4j-jul-2.1.jar
      - /home/pi/currentcost/lib/log4j-slf4j-impl-2.1.jar
      - /home/pi/currentcost/lib/mqtt-client-0.4.0.jar
      - /home/pi/currentcost/lib/reflections-0.9.8.jar
      - /home/pi/currentcost/lib/simple-xml-2.7.1.jar
      - /home/pi/currentcost/lib/slf4j-api-1.7.7.jar
      - /home/pi/currentcost/lib/xml-apis-1.0.b2.jar
      - /home/pi/currentcost/lib/xpp3-1.1.3.3.jar

0 [main] INFO org.tensin.ccf.boot.CurrentCostForwarder - Manifest :
     Manifest-Version: 1.0
     Implementation-Title: current-cost-forwarder
     Implementation-Version: 1.0.0-SNAPSHOT
     Main-Class: org.tensin.ccf.boot.CurrentCostForwarder

00:18:50.227 [main] INFO  org.tensin.ccf.CurrentCostForwarder - Debug activated
00:18:50.271 [main] INFO  org.tensin.ccf.CurrentCostForwarder - Writing retrieved PID [10731] in PID file [./current-cost-forwarder.pid]
00:18:50.338 [main] INFO  org.tensin.ccf.CurrentCostForwarder - Now starting CurrentCostForwarder
00:18:50.412 [main] INFO  org.tensin.ccf.forwarder.mqtt.ForwarderMQTT - Starting MQTT forwarder with topic base name [metrics/current-cost], mqtt broker MQTTBrokerDefinition : broker-auth [false], broker-url [tcp://127.0.0.1:1883], broker-password []
00:18:50.460 [main] INFO  org.tensin.ccf.forwarder.mqtt.ForwarderMQTT - Now starting MQTT client on broker url [tcp://127.0.0.1:1883], client ID is [pi.1423181930456], without authentification
00:18:50.674 [main] INFO  org.tensin.ccf.CurrentCostForwarder - Now starting reader
00:18:50.684 [main] INFO  org.tensin.ccf.reader.CurrentCostReader - Trying to autodect mirror4j device in [/dev/] with pattern [ttyUSB.*]
00:18:50.782 [main] INFO  org.tensin.ccf.reader.CurrentCostReader - Auto-detected current cost device [/dev/ttyUSB0]
00:18:50.900 [main] INFO  org.tensin.ccf.reader.CurrentCostReader - Starting CurrentCostForwarder reader thread on device [/dev/ttyUSB0]
00:18:50.902 [main] INFO  org.tensin.ccf.CurrentCostForwarder - CurrentCostForwarder started in [564ms]
00:18:50.905 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
00:18:51.000 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
00:18:51.100 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
00:18:51.200 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
00:18:51.300 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
00:18:51.400 [THREAD-CURRENT-COST-FORWARDER-READER] INFO  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified device [/dev/ttyUSB0]
00:18:51.500 [THREAD-CURRENT-COST-FORWARDER-READER] INFO

**Comment by SR-G** [comment]
Hey again, 
I've uploaded a new snapshot distribution. It won't correct your problem as i have no clue what's going on on your side, but there are a few additionnal debug logs and some global exceptions betterly catchted that could now help to understand what's happening.

Could you please try that distribution (still with --debug) and give me back the log ?
(still the same link than before, https://github.com/SR-G/current-cost-forwarder/releases/download/1.0.0-SNAPSHOT/current-cost-forwarder-1.0.0-SNAPSHOT.zip )

**Comment by elyobelyob** [comment]
I only have ttyUSB0 .. no more shown.

pi@raspberrypi ~/currentcost $ ./current-cost-forwarder.sh --debug
0 [main] INFO org.tensin.ccf.boot.CurrentCostForwarder - Classpath :
     initial classpath=
      - /home/pi/currentcost/lib/current-cost-forwarder-1.0.0-SNAPSHOT.jar
     dynamic classpath=
      - /home/pi/currentcost/lib/commons-collections-3.2.1.jar
      - /home/pi/currentcost/lib/commons-io-2.4.jar
      - /home/pi/currentcost/lib/commons-lang3-3.1.jar
      - /home/pi/currentcost/lib/commons-logging-1.2.jar
      - /home/pi/currentcost/lib/commons-net-3.2.jar
      - /home/pi/currentcost/lib/dom4j-1.6.1.jar
      - /home/pi/currentcost/lib/guava-17.0.jar
      - /home/pi/currentcost/lib/javassist-3.12.1.GA.jar
      - /home/pi/currentcost/lib/jcommander-1.30.jar
      - /home/pi/currentcost/lib/log4j-1.2-api-2.1.jar
      - /home/pi/currentcost/lib/log4j-api-2.1.jar
      - /home/pi/currentcost/lib/log4j-core-2.1.jar
      - /home/pi/currentcost/lib/log4j-jcl-2.1.jar
      - /home/pi/currentcost/lib/log4j-jul-2.1.jar
      - /home/pi/currentcost/lib/log4j-slf4j-impl-2.1.jar
      - /home/pi/currentcost/lib/mqtt-client-0.4.0.jar
      - /home/pi/currentcost/lib/reflections-0.9.8.jar
      - /home/pi/currentcost/lib/simple-xml-2.7.1.jar
      - /home/pi/currentcost/lib/slf4j-api-1.7.7.jar
      - /home/pi/currentcost/lib/xml-apis-1.0.b2.jar

0 [main] INFO org.tensin.ccf.boot.CurrentCostForwarder - Manifest :
     Manifest-Version: 1.0
     Implementation-Title: current-cost-forwarder
     Implementation-Version: 1.0.0-SNAPSHOT
     Main-Class: org.tensin.ccf.boot.CurrentCostForwarder
     Source-Compatibility: 1.6
     Target-Compatibility: 1.6
     Built-JDK: 1.6.0_45
     Built-Date: Fri Feb 06 14:15:17 CET 2015

14:47:18.578 [main] INFO  org.tensin.ccf.CurrentCostForwarder - Debug
activated
14:47:18.621 [main] INFO  org.tensin.ccf.CurrentCostForwarder - Writing
retrieved PID [27352] in PID file [./current-cost-forwarder.pid]
14:47:18.688 [main] INFO  org.tensin.ccf.CurrentCostForwarder - Now
starting CurrentCostForwarder
14:47:18.693 [main] INFO  org.tensin.ccf.forwarder.console.ForwarderConsole
- Starting ForwarderConsole
  14:47:18.769 [main] INFO  org.tensin.ccf.forwarder.mqtt.ForwarderMQTT -
  Starting MQTT forwarder with topic base name [metrics/current-cost], mqtt
  broker MQTTBrokerDefinition : broker-auth [false], broker-url [tcp://
  127.0.0.1:1883], broker-password []
  14:47:18.817 [main] INFO  org.tensin.ccf.forwarder.mqtt.ForwarderMQTT - Now
  starting MQTT client on broker url [tcp://127.0.0.1:1883], client ID is
  [pi.1423234038813], without authentification
  14:47:19.042 [main] INFO  org.tensin.ccf.CurrentCostForwarder - Activated
  forwarders are [FORWARDER-CONSOLE, FORWARDER-MQTT]
  14:47:19.044 [main] INFO  org.tensin.ccf.CurrentCostForwarder - Now
  starting reader
  14:47:19.054 [main] INFO  org.tensin.ccf.reader.CurrentCostReader - Trying
  to autodect mirror4j device in [/dev/] with pattern [ttyUSB.*]
  14:47:19.153 [main] INFO  org.tensin.ccf.reader.CurrentCostReader -
  Auto-detected current cost device [/dev/ttyUSB0]
  14:47:19.275 [main] INFO  org.tensin.ccf.reader.CurrentCostReader -
  Starting CurrentCostForwarder reader thread on device [/dev/ttyUSB0]
  14:47:19.277 [main] INFO  org.tensin.ccf.CurrentCostForwarder -
  CurrentCostForwarder started in [588ms]
  14:47:19.279 [THREAD-CURRENT-COST-FORWARDER-READER] INFO
  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified
  device [/dev/ttyUSB0]
  14:47:19.280 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG
  org.tensin.ccf.reader.CurrentCostReader - Now starting acquisition from
  device
  14:47:19.380 [THREAD-CURRENT-COST-FORWARDER-READER] INFO
  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified
  device [/dev/ttyUSB0]
  14:47:19.381 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG
  org.tensin.ccf.reader.CurrentCostReader - Now starting acquisition from
  device
  14:47:19.480 [THREAD-CURRENT-COST-FORWARDER-READER] INFO
  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified
  device [/dev/ttyUSB0]
  14:47:19.481 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG
  org.tensin.ccf.reader.CurrentCostReader - Now starting acquisition from
  device
  14:47:19.580 [THREAD-CURRENT-COST-FORWARDER-READER] INFO
  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified
  device [/dev/ttyUSB0]
  14:47:19.581 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG
  org.tensin.ccf.reader.CurrentCostReader - Now starting acquisition from
  device
  14:47:19.680 [THREAD-CURRENT-COST-FORWARDER-READER] INFO
  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified
  device [/dev/ttyUSB0]
  14:47:19.681 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG
  org.tensin.ccf.reader.CurrentCostReader - Now starting acquisition from
  device
  14:47:19.780 [THREAD-CURRENT-COST-FORWARDER-READER] INFO
  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified
  device [/dev/ttyUSB0]
  14:47:19.781 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG
  org.tensin.ccf.reader.CurrentCostReader - Now starting acquisition from
  device
  14:47:19.880 [THREAD-CURRENT-COST-FORWARDER-READER] INFO
  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified
  device [/dev/ttyUSB0]
  14:47:19.881 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG
  org.tensin.ccf.reader.CurrentCostReader - Now starting acquisition from
  device
  14:47:19.980 [THREAD-CURRENT-COST-FORWARDER-READER] INFO
  org.tensin.ccf.reader.CurrentCostReader - Now connected on specified
  device [/dev/ttyUSB0]
  14:47:19.981 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG
  org.tensin.ccf.reader.CurrentCostReader - Now starting acquisition from
  device

**Comment by SR-G** [comment]
I'm really lost :(
Everything seems to be fine on your side, i don't see why the code is behaving that way (no exception, error on the CurrentCostReader > FileInputStream.read() method on the device ...
Which java version are you running ?

<pre>cubox-i# java -version
java version "1.7.0_71"
Java(TM) SE Embedded Runtime Environment (build 1.7.0_71-b14, headless)
Java HotSpot(TM) Embedded Client VM (build 24.71-b01, mixed mode)
</pre>

On my side i don't un with an openjdk implementation but with a JRE provided by Oracle.

**Comment by elyobelyob** [comment]
pi@raspberrypi ~/currentcost $ java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)

**Comment by SR-G** [comment]
I'll try with a jre 1.8.0 but would be surprised to be the problem.
Are you running the program as root ?
Otherwise (as stated in the doc) you have to put 666 permissions on the device (chmod a+r,a+w /dev/ttyUBS0).

**Comment by elyobelyob** [comment]
Interestingly, it now says this .. is this good news?

20:02:07.597 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG org.tensin.ccf.reader.CurrentCostReader - Just received some characters from device
20:02:07.598 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG org.tensin.ccf.reader.CurrentCostReader - Just received some characters from device
20:02:07.598 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG org.tensin.ccf.reader.CurrentCostReader - Just received some characters from device
20:02:07.598 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG org.tensin.ccf.reader.CurrentCostReader - Just received some characters from device
20:02:07.598 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG org.tensin.ccf.reader.CurrentCostReader - Just received some characters from device
20:02:07.598 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG org.tensin.ccf.reader.CurrentCostReader - Just received some characters from device
20:02:07.598 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG org.tensin.ccf.reader.CurrentCostReader - Just received some characters from device
20:02:07.598 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG org.tensin.ccf.reader.CurrentCostReader - Just received some characters from device
20:02:07.598 [THREAD-CURRENT-COST-FORWARDER-READER] DEBUG org.tensin.ccf.reader.CurrentCostReader - Just received some characters from device

**Comment by SR-G** [comment]
Hey, if you are still interested, the problem you had in the end (connection ok but no messages decode) may have been resolved (see other issue https://github.com/SR-G/current-cost-forwarder/issues/2) (was a different separator between my (old) current cost and new ones).

**Comment by elyobelyob** [comment]
Great thanks. I am now receiving data through. Unfortunately it's all gobbledegook. I've ordered a new CC cable, as this one may have got damaged when it fell out. Alternatively, is the baud setting defaulted or needs to be manually set?

**Comment by SR-G** [comment]
Hey. About baud rate setting : it is invisible from the program view (which only use an usb device) and as far as i know, dealed only inside the linux device layer used with the RS232 <> USB adapter.
You can check your device baud rate with : stty -F /dev/ttyUSB0
Or change it with : stty -F /dev/ttyUSB0 115200
(but on my side, no need to change anything about this).

What do you mean by gobbledegook, could you post some log (in debug mode, with today .zip) ?

**Comment by elyobelyob** [comment]
Give me a few days for the replacement cable. It was giving me spurious
results under python as well. Cable fell apart.

**Comment by elyobelyob** [comment]
OK, all working. Looks like the cable was also slightly dodgy and was corrupting the data.

**Comment by SR-G** [comment]
Great to hear that. Closing the issue.
